[build]
    command = "npm run build"

[build.environment]
    VARIABLE = "value"

[context.context.environment]
    NODE_ENV = "development"

[context.context]
    command = "echo $NODE_ENV && npm run build"

[context.branch-deploy.environment]
    ACCESS_TOKEN = "super secret"

[context.deploy-preview]
    command = "echo 'Something' && npm run build"